### In this notebook, we will experiment with function pipe in Python, similar to R x |> f1 |> f2

In [1]:
print("Hello world")

Hello world


In [2]:
double_fn = lambda x: x*2
double_fn(100) # should be 200

200

In [3]:
square_fn = lambda x: x**2
square_fn(10) # should be 100

100

In [4]:
x = 10
double_fn(square_fn(x)) # should be 10 |> square() |> double = 200

200

In [5]:
type(double_fn)

function

In [6]:
class Pipe:
    input: None

    def __init__(self, input):
        self.input = input

    def then(self, func, *args):
        return Pipe(func(self.input, *args))

    def __call__(self, func, *args):
        return self.then(func, *args)

    def __str__(self):
        return str(self.input)
    
    @property
    def output(self):
        return self.input

        

In [7]:
print("X =", x)
pipe = Pipe(x)
print(pipe.then(double_fn))

X = 10
20


In [8]:
print(pipe(double_fn))

20


In [9]:
print(pipe.then(double_fn).then(square_fn)) # 20 -> double -> square = 20*20 = 400

400


In [10]:
print(Pipe(10).then(square_fn).then(double_fn)) # 10 -> square -> double = 100 * 2 = 200

200


In [11]:
# more complex operations
add_fn = lambda x, y: x + y

print(Pipe(10).then(add_fn, 20).then(double_fn)) # 10 + 20 -> double = 60

60


In [12]:
# a full flavor test with numpy
import numpy as np

In [16]:
# standard operation
numbers = [1, 2, 3, 4, 5]
# double, then square
result = np.multiply(numbers, 2)
print(result)
result = np.square(result)
print(result)

[ 2  4  6  8 10]
[  4  16  36  64 100]


In [14]:
# shorter implementation, but harder to read
results = np.square(np.multiply(numbers, 2))
print(results)

[  4  16  36  64 100]


In [17]:
# using pipe
Pipe(numbers).then(np.multiply, 2).then(np.square).output

array([  4,  16,  36,  64, 100])

In [18]:
s = "Hello world"
print(s)

Hello world


In [40]:
upper = lambda s, i: s[0:i]+s[i].upper()+s[i+1:]
reverse = lambda s: s[::-1]

Pipe(s).then(upper, 1).then(reverse).output

'dlrow ollEH'

In [41]:
s1 = upper(s, 1)
s2 = reverse(s1)
print(s2)

dlrow ollEH


In [42]:
print(reverse(upper(s, 1)))

dlrow ollEH


In [43]:
Pipe(s).then(reverse).then(reverse).then(upper,4).output

'HellO world'